development:
  adapter: postgresql
  encoding: unicode
  database: invest_development
  pool: 5
  username:
  password:

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: invest_test
  pool: 5
  username:
  password:

# Configure the database used when in the production environment
production:
  adapter: postgresql
  encoding: unicode
  database: invest_production
  pool: 5
  username:
  password:
  url: <%= ENV['DATABASE_URL'] %>
